<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Department;
use App\Models\State;
use App\Models\ScrapingSource;
use Illuminate\Database\Seeder;

class OfficialGovSourcesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 1. Create States and UTs (All 28 States + 8 UTs + Pan India Central)
        $statePanIndia = State::firstOrCreate(['name' => 'Pan India Central'], ['code' => 'CENTRAL']);
        $stateAP = State::firstOrCreate(['name' => 'Andhra Pradesh'], ['code' => 'AP']);
        $stateAR = State::firstOrCreate(['name' => 'Arunachal Pradesh'], ['code' => 'AR']);
        $stateAS = State::firstOrCreate(['name' => 'Assam'], ['code' => 'AS']);
        $stateBR = State::firstOrCreate(['name' => 'Bihar'], ['code' => 'BR']);
        $stateCG = State::firstOrCreate(['name' => 'Chhattisgarh'], ['code' => 'CG']);
        $stateGoa = State::firstOrCreate(['name' => 'Goa'], ['code' => 'GA']);
        $stateGJ = State::firstOrCreate(['name' => 'Gujarat'], ['code' => 'GJ']);
        $stateHR = State::firstOrCreate(['name' => 'Haryana'], ['code' => 'HR']);
        $stateHP = State::firstOrCreate(['name' => 'Himachal Pradesh'], ['code' => 'HP']);
        $stateJH = State::firstOrCreate(['name' => 'Jharkhand'], ['code' => 'JH']);
        $stateKar = State::firstOrCreate(['name' => 'Karnataka'], ['code' => 'KA']);
        $stateKL = State::firstOrCreate(['name' => 'Kerala'], ['code' => 'KL']);
        $stateMP = State::firstOrCreate(['name' => 'Madhya Pradesh'], ['code' => 'MP']);
        $stateMaha = State::firstOrCreate(['name' => 'Maharashtra'], ['code' => 'MH']);
        $stateMN = State::firstOrCreate(['name' => 'Manipur'], ['code' => 'MN']);
        $stateML = State::firstOrCreate(['name' => 'Meghalaya'], ['code' => 'ML']);
        $stateMZ = State::firstOrCreate(['name' => 'Mizoram'], ['code' => 'MZ']);
        $stateNL = State::firstOrCreate(['name' => 'Nagaland'], ['code' => 'NL']);
        $stateOD = State::firstOrCreate(['name' => 'Odisha'], ['code' => 'OD']);
        $statePB = State::firstOrCreate(['name' => 'Punjab'], ['code' => 'PB']);
        $stateRJ = State::firstOrCreate(['name' => 'Rajasthan'], ['code' => 'RJ']);
        $stateSK = State::firstOrCreate(['name' => 'Sikkim'], ['code' => 'SK']);
        $stateTN = State::firstOrCreate(['name' => 'Tamil Nadu'], ['code' => 'TN']);
        $stateTG = State::firstOrCreate(['name' => 'Telangana'], ['code' => 'TG']);
        $stateTR = State::firstOrCreate(['name' => 'Tripura'], ['code' => 'TR']);
        $stateUP = State::firstOrCreate(['name' => 'Uttar Pradesh'], ['code' => 'UP']);
        $stateUK = State::firstOrCreate(['name' => 'Uttarakhand'], ['code' => 'UK']);
        $stateWB = State::firstOrCreate(['name' => 'West Bengal'], ['code' => 'WB']);

        // UTs
        $stateAN = State::firstOrCreate(['name' => 'Andaman and Nicobar Islands'], ['code' => 'AN']);
        $stateCH = State::firstOrCreate(['name' => 'Chandigarh'], ['code' => 'CH']);
        $stateDN = State::firstOrCreate(['name' => 'Dadra and Nagar Haveli and Daman and Diu'], ['code' => 'DN']);
        $stateDelhi = State::firstOrCreate(['name' => 'Delhi NCT'], ['code' => 'DL']);
        $stateJK = State::firstOrCreate(['name' => 'Jammu and Kashmir'], ['code' => 'JK']);
        $stateLA = State::firstOrCreate(['name' => 'Ladakh'], ['code' => 'LA']);
        $stateLD = State::firstOrCreate(['name' => 'Lakshadweep'], ['code' => 'LD']);
        $statePY = State::firstOrCreate(['name' => 'Puducherry'], ['code' => 'PY']);

        // 2. Create Sector Categories
        $catCivil = Category::firstOrCreate(['slug' => 'upsc-ssc-jobs'], ['name' => 'UPSC & SSC Jobs']);
        $catBank = Category::firstOrCreate(['slug' => 'banking-finance'], ['name' => 'Banking & Finance']);
        $catRail = Category::firstOrCreate(['slug' => 'railway-jobs'], ['name' => 'Railways (RRB)']);
        $catDef = Category::firstOrCreate(['slug' => 'defense-jobs'], ['name' => 'Defense & Police']);
        $catJudicial = Category::firstOrCreate(['slug' => 'judicial-services'], ['name' => 'Judicial Services']);
        $catMunicipal = Category::firstOrCreate(['slug' => 'municipal-local-boards'], ['name' => 'Municipal & Local Boards']);
        $catPsu = Category::firstOrCreate(['slug' => 'psu-corporate-jobs'], ['name' => 'PSU & Corporate Jobs']);
        $catAcademic = Category::firstOrCreate(['slug' => 'academic-research'], ['name' => 'Academic & Research']);
        $catNatural = Category::firstOrCreate(['slug' => 'natural-resources'], ['name' => 'Natural Resources']);
        $catHealth = Category::firstOrCreate(['slug' => 'health-services'], ['name' => 'Health Services']);

        // 3. Create Departments (Existing + New)
        $deptUPSC = Department::firstOrCreate(['name' => 'Union Public Service Commission'], ['code' => 'UPSC']);
        $deptSSC = Department::firstOrCreate(['name' => 'Staff Selection Commission'], ['code' => 'SSC']);
        $deptSBI = Department::firstOrCreate(['name' => 'State Bank of India'], ['code' => 'SBI']);
        $deptRBI = Department::firstOrCreate(['name' => 'Reserve Bank of India'], ['code' => 'RBI']);
        $deptIBPS = Department::firstOrCreate(['name' => 'Institute of Banking Personnel Selection'], ['code' => 'IBPS']);
        $deptNABARD = Department::firstOrCreate(['name' => 'NABARD Board'], ['code' => 'NABARD']);
        $deptRRB = Department::firstOrCreate(['name' => 'Railway Recruitment Board'], ['code' => 'RRB']);
        $deptDHC = Department::firstOrCreate(['name' => 'Delhi High Court Board'], ['code' => 'DHC']);
        $deptAHC = Department::firstOrCreate(['name' => 'Allahabad High Court Board'], ['code' => 'AHC']);
        $deptDDC = Department::firstOrCreate(['name' => 'Delhi District Courts Board'], ['code' => 'DDC']);
        $deptMCD = Department::firstOrCreate(['name' => 'Municipal Corporation of Delhi'], ['code' => 'MCD']);
        $deptBMC = Department::firstOrCreate(['name' => 'Brihanmumbai Municipal Corporation'], ['code' => 'BMC']);
        $deptPuneSC = Department::firstOrCreate(['name' => 'Pune Smart City Corporation'], ['code' => 'PUNE-SC']);
        $deptBlrSC = Department::firstOrCreate(['name' => 'Bengaluru Smart City Board'], ['code' => 'BLR-SC']);
        $deptONGC = Department::firstOrCreate(['name' => 'Oil and Natural Gas Corporation'], ['code' => 'ONGC']);
        $deptNTPC = Department::firstOrCreate(['name' => 'National Thermal Power Corporation'], ['code' => 'NTPC']);
        $deptBHEL = Department::firstOrCreate(['name' => 'Bharat Heavy Electricals Limited'], ['code' => 'BHEL']);
        $deptGAIL = Department::firstOrCreate(['name' => 'GAIL India Limited'], ['code' => 'GAIL']);
        $deptIOCL = Department::firstOrCreate(['name' => 'Indian Oil Corporation Limited'], ['code' => 'IOCL']);
        $deptDU = Department::firstOrCreate(['name' => 'Delhi University Board'], ['code' => 'DU']);
        $deptJNU = Department::firstOrCreate(['name' => 'Jawaharlal Nehru University Board'], ['code' => 'JNU']);
        $deptAIIMS = Department::firstOrCreate(['name' => 'AIIMS Delhi Board'], ['code' => 'AIIMS']);
        $deptPGIMER = Department::firstOrCreate(['name' => 'PGIMER Chandigarh Board'], ['code' => 'PGIMER']);
        $deptDRDO = Department::firstOrCreate(['name' => 'Defence Research and Development Organisation'], ['code' => 'DRDO']);
        $deptArmy = Department::firstOrCreate(['name' => 'Indian Army Board'], ['code' => 'ARMY']);
        $deptUPPBPB = Department::firstOrCreate(['name' => 'Uttar Pradesh Police Recruitment Board'], ['code' => 'UPPBPB']);
        $deptKSP = Department::firstOrCreate(['name' => 'Karnataka State Police Board'], ['code' => 'KSP']);
        $deptICAR = Department::firstOrCreate(['name' => 'Indian Council of Agricultural Research'], ['code' => 'ICAR']);
        $deptIFS = Department::firstOrCreate(['name' => 'Indian Forest Service Board'], ['code' => 'IFS']);
        $deptCoal = Department::firstOrCreate(['name' => 'Coal India Limited Board'], ['code' => 'CIL']);
        $deptNMDC = Department::firstOrCreate(['name' => 'NMDC Limited Board'], ['code' => 'NMDC']);
        $deptNHM = Department::firstOrCreate(['name' => 'National Health Mission'], ['code' => 'NHM']);
        $deptKVS = Department::firstOrCreate(['name' => 'Kendriya Vidyalaya Sangathan'], ['code' => 'KVS']);
        $deptISRO = Department::firstOrCreate(['name' => 'Indian Space Research Organisation'], ['code' => 'ISRO']);
        $deptCSIR = Department::firstOrCreate(['name' => 'Council of Scientific and Industrial Research'], ['code' => 'CSIR']);
        $deptDSC = Department::firstOrCreate(['name' => 'District Selection Committee'], ['code' => 'DSC']);
        $deptGPSC = Department::firstOrCreate(['name' => 'Goa Public Service Commission'], ['code' => 'GPSC']);
        $deptUPPSC = Department::firstOrCreate(['name' => 'Uttar Pradesh Public Service Commission'], ['code' => 'UPPSC']);

        // New Departments
        $deptBARC = Department::firstOrCreate(['name' => 'Bhabha Atomic Research Centre'], ['code' => 'BARC']);
        $deptICMR = Department::firstOrCreate(['name' => 'Indian Council of Medical Research'], ['code' => 'ICMR']);
        $deptNTA = Department::firstOrCreate(['name' => 'National Testing Agency'], ['code' => 'NTA']);
        $deptNPCIL = Department::firstOrCreate(['name' => 'Nuclear Power Corporation of India Limited'], ['code' => 'NPCIL']);
        $deptBEL = Department::firstOrCreate(['name' => 'Bharat Electronics Limited'], ['code' => 'BEL']);
        $deptHAL = Department::firstOrCreate(['name' => 'Hindustan Aeronautics Limited'], ['code' => 'HAL']);
        $deptBPCL = Department::firstOrCreate(['name' => 'Bharat Petroleum Corporation Limited'], ['code' => 'BPCL']);
        $deptHPCL = Department::firstOrCreate(['name' => 'Hindustan Petroleum Corporation Limited'], ['code' => 'HPCL']);
        $deptPGCIL = Department::firstOrCreate(['name' => 'Power Grid Corporation of India'], ['code' => 'PGCIL']);
        $deptNHPC = Department::firstOrCreate(['name' => 'NHPC Limited'], ['code' => 'NHPC']);
        $deptAAI = Department::firstOrCreate(['name' => 'Airports Authority of India'], ['code' => 'AAI']);
        $deptFCI = Department::firstOrCreate(['name' => 'Food Corporation of India'], ['code' => 'FCI']);
        $deptESIC = Department::firstOrCreate(['name' => 'Employees State Insurance Corporation'], ['code' => 'ESIC']);
        $deptEPFO = Department::firstOrCreate(['name' => 'Employees Provident Fund Organisation'], ['code' => 'EPFO']);
        $deptNavy = Department::firstOrCreate(['name' => 'Indian Navy Board'], ['code' => 'NAVY']);
        $deptIAF = Department::firstOrCreate(['name' => 'Indian Air Force Board'], ['code' => 'IAF']);
        $deptICG = Department::firstOrCreate(['name' => 'Indian Coast Guard Board'], ['code' => 'ICG']);
        $deptBSF = Department::firstOrCreate(['name' => 'Border Security Force'], ['code' => 'BSF']);
        $deptCRPF = Department::firstOrCreate(['name' => 'Central Reserve Police Force'], ['code' => 'CRPF']);
        $deptCISF = Department::firstOrCreate(['name' => 'Central Industrial Security Force'], ['code' => 'CISF']);
        $deptITBP = Department::firstOrCreate(['name' => 'Indo-Tibetan Border Police'], ['code' => 'ITBP']);
        $deptSSB = Department::firstOrCreate(['name' => 'Sashastra Seema Bal'], ['code' => 'SSB']);
        $deptAR = Department::firstOrCreate(['name' => 'Assam Rifles Board'], ['code' => 'AR']);
        
        // State PSCs
        $deptAPPSC = Department::firstOrCreate(['name' => 'Andhra Pradesh Public Service Commission'], ['code' => 'APPSC']);
        $deptAPSC = Department::firstOrCreate(['name' => 'Assam Public Service Commission'], ['code' => 'APSC']);
        $deptBPSC = Department::firstOrCreate(['name' => 'Bihar Public Service Commission'], ['code' => 'BPSC']);
        $deptCGPSC = Department::firstOrCreate(['name' => 'Chhattisgarh Public Service Commission'], ['code' => 'CGPSC']);
        $deptGPSCGJ = Department::firstOrCreate(['name' => 'Gujarat Public Service Commission'], ['code' => 'GPSC-GJ']);
        $deptHPSC = Department::firstOrCreate(['name' => 'Haryana Public Service Commission'], ['code' => 'HPSC']);
        $deptHPPSC = Department::firstOrCreate(['name' => 'Himachal Pradesh Public Service Commission'], ['code' => 'HPPSC']);
        $deptJPSC = Department::firstOrCreate(['name' => 'Jharkhand Public Service Commission'], ['code' => 'JPSC']);
        $deptKPSC = Department::firstOrCreate(['name' => 'Karnataka Public Service Commission'], ['code' => 'KPSC']);
        $deptKeralapsc = Department::firstOrCreate(['name' => 'Kerala Public Service Commission'], ['code' => 'KERALAPSC']);
        $deptMPPSC = Department::firstOrCreate(['name' => 'Madhya Pradesh Public Service Commission'], ['code' => 'MPPSC']);
        $deptMPSC = Department::firstOrCreate(['name' => 'Maharashtra Public Service Commission'], ['code' => 'MPSC']);
        $deptOPSC = Department::firstOrCreate(['name' => 'Odisha Public Service Commission'], ['code' => 'OPSC']);
        $deptPPSC = Department::firstOrCreate(['name' => 'Punjab Public Service Commission'], ['code' => 'PPSC']);
        $deptRPSC = Department::firstOrCreate(['name' => 'Rajasthan Public Service Commission'], ['code' => 'RPSC']);
        $deptTNPSC = Department::firstOrCreate(['name' => 'Tamil Nadu Public Service Commission'], ['code' => 'TNPSC']);
        $deptTSPSC = Department::firstOrCreate(['name' => 'Telangana State Public Service Commission'], ['code' => 'TSPSC']);
        $deptWBPSC = Department::firstOrCreate(['name' => 'West Bengal Public Service Commission'], ['code' => 'WBPSC']);

        // 4. Source Definitions (Official Gov Ingestion Sources)
        $sources = [
            // --- CENTRAL GOVERNMENT ---
            [
                'name' => 'UPSC Official Recruitment Feed',
                'source_url' => 'https://upsc.gov.in/recruitment/active-jobs-feed',
                'selectors_config' => [
                    'driver' => 'upsc',
                    'official_url' => 'https://upsc.gov.in',
                    'notification_page' => 'https://upsc.gov.in/recruitment/active-jobs',
                    'update_frequency' => 'daily',
                    'authentication_type' => 'none',
                    'rss_availability' => 'yes',
                    'formats' => ['HTML', 'RSS', 'XML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'high',
                    'crawler_type' => 'http',
                    'item_selector' => 'table.views-table tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.last-date',
                    'default_category_id' => $catCivil->id,
                    'default_department_id' => $deptUPSC->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '*/5 * * * *',
            ],
            [
                'name' => 'SSC Staff Selection Board',
                'source_url' => 'https://ssc.gov.in/portal/active-recruitments',
                'selectors_config' => [
                    'driver' => 'ssc',
                    'official_url' => 'https://ssc.gov.in',
                    'notification_page' => 'https://ssc.gov.in/portal/active-recruitments',
                    'update_frequency' => 'daily',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'yes',
                    'priority' => 'high',
                    'crawler_type' => 'playwright',
                    'item_selector' => 'table.ssc-table tbody tr',
                    'title_selector' => 'td.job-title',
                    'deadline_selector' => 'td.deadline',
                    'default_category_id' => $catCivil->id,
                    'default_department_id' => $deptSSC->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 0 * * *',
            ],
            [
                'name' => 'RBI Opportunities recruitment',
                'source_url' => 'https://opportunities.rbi.org.in/scripts/vacancies.aspx',
                'selectors_config' => [
                    'driver' => 'banking',
                    'official_url' => 'https://rbi.org.in',
                    'notification_page' => 'https://opportunities.rbi.org.in/scripts/vacancies.aspx',
                    'update_frequency' => 'daily',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'high',
                    'crawler_type' => 'http',
                    'item_selector' => 'table tr.rbi-row',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.date',
                    'default_category_id' => $catBank->id,
                    'default_department_id' => $deptRBI->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 6 * * *',
            ],
            [
                'name' => 'IBPS Careers Opportunities',
                'source_url' => 'https://www.ibps.in/career-opportunities/',
                'selectors_config' => [
                    'driver' => 'banking',
                    'official_url' => 'https://ibps.in',
                    'notification_page' => 'https://www.ibps.in/career-opportunities/',
                    'update_frequency' => 'daily',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'high',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.ibps-job',
                    'title_selector' => 'a.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catBank->id,
                    'default_department_id' => $deptIBPS->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 6 * * *',
            ],

            // --- DEFENCE & POLICE ---
            [
                'name' => 'Indian Army Join Military Feed',
                'source_url' => 'https://joinindianarmy.nic.in/recruitment-board',
                'selectors_config' => [
                    'driver' => 'defence',
                    'official_url' => 'https://joinindianarmy.nic.in',
                    'notification_page' => 'https://joinindianarmy.nic.in/recruitment-board',
                    'update_frequency' => 'daily',
                    'authentication_type' => 'captcha',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'yes',
                    'is_dynamic' => 'yes',
                    'priority' => 'high',
                    'crawler_type' => 'puppeteer',
                    'item_selector' => 'div.army-job',
                    'title_selector' => 'a.army-title',
                    'deadline_selector' => 'span.army-date',
                    'default_category_id' => $catDef->id,
                    'default_department_id' => $deptArmy->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 8 * * *',
            ],
            [
                'name' => 'Indian Navy Careers',
                'source_url' => 'https://joinindiannavy.gov.in/join-navy/ways-to-join',
                'selectors_config' => [
                    'driver' => 'defence',
                    'official_url' => 'https://joinindiannavy.gov.in',
                    'notification_page' => 'https://joinindiannavy.gov.in/join-navy/ways-to-join',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'yes',
                    'priority' => 'high',
                    'crawler_type' => 'playwright',
                    'item_selector' => 'div.navy-job',
                    'title_selector' => 'h3.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catDef->id,
                    'default_department_id' => $deptNavy->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 8 * * *',
            ],
            [
                'name' => 'Indian Air Force recruitment',
                'source_url' => 'https://careerindianairforce.cdac.in/join-iaf',
                'selectors_config' => [
                    'driver' => 'defence',
                    'official_url' => 'https://careerindianairforce.cdac.in',
                    'notification_page' => 'https://careerindianairforce.cdac.in/join-iaf',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'yes',
                    'priority' => 'high',
                    'crawler_type' => 'playwright',
                    'item_selector' => 'div.iaf-job',
                    'title_selector' => 'h3.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catDef->id,
                    'default_department_id' => $deptIAF->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 8 * * *',
            ],
            [
                'name' => 'Indian Coast Guard Opportunities',
                'source_url' => 'https://joinindiancoastguard.cdac.in/join-cg',
                'selectors_config' => [
                    'driver' => 'defence',
                    'official_url' => 'https://joinindiancoastguard.cdac.in',
                    'notification_page' => 'https://joinindiancoastguard.cdac.in/join-cg',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'yes',
                    'priority' => 'medium',
                    'crawler_type' => 'playwright',
                    'item_selector' => 'div.icg-job',
                    'title_selector' => 'h3.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catDef->id,
                    'default_department_id' => $deptICG->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 9 * * *',
            ],
            [
                'name' => 'BSF Active Recruitments',
                'source_url' => 'https://rectt.bsf.gov.in/active-recruitments',
                'selectors_config' => [
                    'driver' => 'defence',
                    'official_url' => 'https://rectt.bsf.gov.in',
                    'notification_page' => 'https://rectt.bsf.gov.in/active-recruitments',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'yes',
                    'priority' => 'high',
                    'crawler_type' => 'playwright',
                    'item_selector' => 'div.bsf-job',
                    'title_selector' => 'h3.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catDef->id,
                    'default_department_id' => $deptBSF->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 9 * * *',
            ],
            [
                'name' => 'CRPF Recruitment Portal',
                'source_url' => 'https://crpf.gov.in/recruitment.htm',
                'selectors_config' => [
                    'driver' => 'defence',
                    'official_url' => 'https://crpf.gov.in',
                    'notification_page' => 'https://crpf.gov.in/recruitment.htm',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.crpf-job',
                    'title_selector' => 'a.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catDef->id,
                    'default_department_id' => $deptCRPF->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 9 * * *',
            ],
            [
                'name' => 'CISF Active Jobs',
                'source_url' => 'https://cisfrectt.cisf.gov.in/active-jobs',
                'selectors_config' => [
                    'driver' => 'defence',
                    'official_url' => 'https://cisfrectt.cisf.gov.in',
                    'notification_page' => 'https://cisfrectt.cisf.gov.in/active-jobs',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'yes',
                    'priority' => 'medium',
                    'crawler_type' => 'playwright',
                    'item_selector' => 'div.cisf-job',
                    'title_selector' => 'h3.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catDef->id,
                    'default_department_id' => $deptCISF->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 10 * * *',
            ],
            [
                'name' => 'ITBP Active Jobs Portal',
                'source_url' => 'https://recruitment.itbpolice.nic.in/active-jobs',
                'selectors_config' => [
                    'driver' => 'defence',
                    'official_url' => 'https://recruitment.itbpolice.nic.in',
                    'notification_page' => 'https://recruitment.itbpolice.nic.in/active-jobs',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'yes',
                    'priority' => 'medium',
                    'crawler_type' => 'playwright',
                    'item_selector' => 'div.itbp-job',
                    'title_selector' => 'h3.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catDef->id,
                    'default_department_id' => $deptITBP->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 10 * * *',
            ],
            [
                'name' => 'SSB Active Jobs Portal',
                'source_url' => 'https://ssbrectt.gov.in/active-jobs',
                'selectors_config' => [
                    'driver' => 'defence',
                    'official_url' => 'https://ssbrectt.gov.in',
                    'notification_page' => 'https://ssbrectt.gov.in/active-jobs',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'yes',
                    'priority' => 'medium',
                    'crawler_type' => 'playwright',
                    'item_selector' => 'div.ssb-job',
                    'title_selector' => 'h3.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catDef->id,
                    'default_department_id' => $deptSSB->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 11 * * *',
            ],
            [
                'name' => 'Assam Rifles Recruitment',
                'source_url' => 'https://assamrifles.gov.in/recruitment',
                'selectors_config' => [
                    'driver' => 'defence',
                    'official_url' => 'https://assamrifles.gov.in',
                    'notification_page' => 'https://assamrifles.gov.in/recruitment',
                    'update_frequency' => 'monthly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'low',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.ar-job',
                    'title_selector' => 'a.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catDef->id,
                    'default_department_id' => $deptAR->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 11 * * *',
            ],
            [
                'name' => 'UP Police Recruitment Board',
                'source_url' => 'https://uppbpb.gov.in/active-recruitments',
                'selectors_config' => [
                    'driver' => 'police',
                    'official_url' => 'https://uppbpb.gov.in',
                    'notification_page' => 'https://uppbpb.gov.in/active-recruitments',
                    'update_frequency' => 'twice_weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML', 'PDF'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'high',
                    'crawler_type' => 'http',
                    'item_selector' => 'table.police-table tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.date',
                    'default_category_id' => $catDef->id,
                    'default_department_id' => $deptUPPBPB->id,
                    'default_state_id' => $stateUP->id,
                ],
                'cron_expression' => '0 9 * * *',
            ],

            // --- CENTRAL RESEARCH / TECHNICAL ---
            [
                'name' => 'DRDO Careers opportunities',
                'source_url' => 'https://www.drdo.gov.in/drdo/careers',
                'selectors_config' => [
                    'driver' => 'academic',
                    'official_url' => 'https://www.drdo.gov.in',
                    'notification_page' => 'https://www.drdo.gov.in/drdo/careers',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'table.drdo-jobs tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.date',
                    'default_category_id' => $catAcademic->id,
                    'default_department_id' => $deptDRDO->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 10 * * *',
            ],
            [
                'name' => 'ISRO Space Careers',
                'source_url' => 'https://isro.gov.in/careers',
                'selectors_config' => [
                    'driver' => 'academic',
                    'official_url' => 'https://isro.gov.in',
                    'notification_page' => 'https://isro.gov.in/careers',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML', 'PDF'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'yes',
                    'priority' => 'high',
                    'crawler_type' => 'playwright',
                    'item_selector' => 'table.isro-table tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.date',
                    'default_category_id' => $catAcademic->id,
                    'default_department_id' => $deptISRO->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 14 * * *',
            ],
            [
                'name' => 'BARC Careers recruitment',
                'source_url' => 'https://www.barc.gov.in/careers/recruitment.html',
                'selectors_config' => [
                    'driver' => 'academic',
                    'official_url' => 'https://www.barc.gov.in',
                    'notification_page' => 'https://www.barc.gov.in/careers/recruitment.html',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.barc-job',
                    'title_selector' => 'a.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catAcademic->id,
                    'default_department_id' => $deptBARC->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 14 * * *',
            ],
            [
                'name' => 'CSIR Careers opportunities',
                'source_url' => 'https://www.csir.res.in/career-opportunities',
                'selectors_config' => [
                    'driver' => 'academic',
                    'official_url' => 'https://www.csir.res.in',
                    'notification_page' => 'https://www.csir.res.in/career-opportunities',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.csir-job',
                    'title_selector' => 'a.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catAcademic->id,
                    'default_department_id' => $deptCSIR->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 15 * * *',
            ],
            [
                'name' => 'ICMR Career Opportunities',
                'source_url' => 'https://main.icmr.nic.in/career-opportunity',
                'selectors_config' => [
                    'driver' => 'academic',
                    'official_url' => 'https://main.icmr.nic.in',
                    'notification_page' => 'https://main.icmr.nic.in/career-opportunity',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.icmr-job',
                    'title_selector' => 'a.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catAcademic->id,
                    'default_department_id' => $deptICMR->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 15 * * *',
            ],
            [
                'name' => 'NTA Jobs recruitment',
                'source_url' => 'https://nta.ac.in/jobs',
                'selectors_config' => [
                    'driver' => 'academic',
                    'official_url' => 'https://nta.ac.in',
                    'notification_page' => 'https://nta.ac.in/jobs',
                    'update_frequency' => 'monthly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'low',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.nta-job',
                    'title_selector' => 'a.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catAcademic->id,
                    'default_department_id' => $deptNTA->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 16 * * *',
            ],

            // --- CENTRAL PSUs ---
            [
                'name' => 'NTPC Career Ingestion Feed',
                'source_url' => 'https://ntpccareers.net/active-jobs',
                'selectors_config' => [
                    'driver' => 'psu',
                    'official_url' => 'https://ntpc.co.in',
                    'notification_page' => 'https://ntpccareers.net',
                    'update_frequency' => 'twice_weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'high',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.ntpc-job',
                    'title_selector' => 'h4.ntpc-title',
                    'deadline_selector' => 'span.ntpc-deadline',
                    'default_category_id' => $catPsu->id,
                    'default_department_id' => $deptNTPC->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 18 * * *',
            ],
            [
                'name' => 'ONGC Recruitment Ingest',
                'source_url' => 'https://ongcindia.com/careers',
                'selectors_config' => [
                    'driver' => 'psu',
                    'official_url' => 'https://ongcindia.com',
                    'notification_page' => 'https://ongcindia.com/careers',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML', 'PDF'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'yes',
                    'priority' => 'high',
                    'crawler_type' => 'playwright',
                    'item_selector' => 'div.ongc-job-row',
                    'title_selector' => 'h3.title',
                    'deadline_selector' => 'span.deadline',
                    'default_category_id' => $catPsu->id,
                    'default_department_id' => $deptONGC->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 6 * * *',
            ],
            [
                'name' => 'Coal India Recruitment Ingest',
                'source_url' => 'https://coalindia.in/careers',
                'selectors_config' => [
                    'driver' => 'natural_resources',
                    'official_url' => 'https://coalindia.in',
                    'notification_page' => 'https://coalindia.in/careers',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'table.coal-jobs tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.deadline',
                    'default_category_id' => $catNatural->id,
                    'default_department_id' => $deptCoal->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 11 * * *',
            ],
            [
                'name' => 'NPCIL Careers portal',
                'source_url' => 'https://www.npcilcareers.co.in',
                'selectors_config' => [
                    'driver' => 'psu',
                    'official_url' => 'https://npcil.co.in',
                    'notification_page' => 'https://www.npcilcareers.co.in',
                    'update_frequency' => 'monthly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.npcil-job',
                    'title_selector' => 'a.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catPsu->id,
                    'default_department_id' => $deptNPCIL->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 18 * * *',
            ],
            [
                'name' => 'BEL Careers opportunities',
                'source_url' => 'https://www.bel-india.in/Careers.aspx',
                'selectors_config' => [
                    'driver' => 'psu',
                    'official_url' => 'https://www.bel-india.in',
                    'notification_page' => 'https://www.bel-india.in/Careers.aspx',
                    'update_frequency' => 'monthly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.bel-job',
                    'title_selector' => 'a.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catPsu->id,
                    'default_department_id' => $deptBEL->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 19 * * *',
            ],
            [
                'name' => 'HAL Careers Opportunities',
                'source_url' => 'https://hal-india.co.in/Careers',
                'selectors_config' => [
                    'driver' => 'psu',
                    'official_url' => 'https://hal-india.co.in',
                    'notification_page' => 'https://hal-india.co.in/Careers',
                    'update_frequency' => 'monthly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.hal-job',
                    'title_selector' => 'a.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catPsu->id,
                    'default_department_id' => $deptHAL->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 19 * * *',
            ],
            [
                'name' => 'GAIL Careers Portal',
                'source_url' => 'https://gailonline.com/CRCheckingey.html',
                'selectors_config' => [
                    'driver' => 'psu',
                    'official_url' => 'https://gailonline.com',
                    'notification_page' => 'https://gailonline.com/CRCheckingey.html',
                    'update_frequency' => 'monthly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.gail-job',
                    'title_selector' => 'a.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catPsu->id,
                    'default_department_id' => $deptGAIL->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 20 * * *',
            ],
            [
                'name' => 'IOCL Latest Job Openings',
                'source_url' => 'https://iocl.com/latest-job-opening',
                'selectors_config' => [
                    'driver' => 'psu',
                    'official_url' => 'https://iocl.com',
                    'notification_page' => 'https://iocl.com/latest-job-opening',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'high',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.iocl-job',
                    'title_selector' => 'a.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catPsu->id,
                    'default_department_id' => $deptIOCL->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 20 * * *',
            ],
            [
                'name' => 'BPCL Careers openings',
                'source_url' => 'https://www.bharatpetroleum.in/careers/current-openings.aspx',
                'selectors_config' => [
                    'driver' => 'psu',
                    'official_url' => 'https://www.bharatpetroleum.in',
                    'notification_page' => 'https://www.bharatpetroleum.in/careers/current-openings.aspx',
                    'update_frequency' => 'monthly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.bpcl-job',
                    'title_selector' => 'a.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catPsu->id,
                    'default_department_id' => $deptBPCL->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 21 * * *',
            ],
            [
                'name' => 'HPCL Careers portal',
                'source_url' => 'https://www.hindustanpetroleum.com/careers',
                'selectors_config' => [
                    'driver' => 'psu',
                    'official_url' => 'https://www.hindustanpetroleum.com',
                    'notification_page' => 'https://www.hindustanpetroleum.com/careers',
                    'update_frequency' => 'monthly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.hpcl-job',
                    'title_selector' => 'a.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catPsu->id,
                    'default_department_id' => $deptHPCL->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 21 * * *',
            ],
            [
                'name' => 'Power Grid Careers Portal',
                'source_url' => 'https://www.powergrid.in/careers',
                'selectors_config' => [
                    'driver' => 'psu',
                    'official_url' => 'https://www.powergrid.in',
                    'notification_page' => 'https://www.powergrid.in/careers',
                    'update_frequency' => 'monthly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.pg-job',
                    'title_selector' => 'a.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catPsu->id,
                    'default_department_id' => $deptPGCIL->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 22 * * *',
            ],
            [
                'name' => 'NHPC Careers Opportunities',
                'source_url' => 'https://www.nhpcindia.com/Default.aspx?id=128&lang=eng',
                'selectors_config' => [
                    'driver' => 'psu',
                    'official_url' => 'https://www.nhpcindia.com',
                    'notification_page' => 'https://www.nhpcindia.com/Default.aspx?id=128&lang=eng',
                    'update_frequency' => 'monthly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.nhpc-job',
                    'title_selector' => 'a.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catPsu->id,
                    'default_department_id' => $deptNHPC->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 22 * * *',
            ],
            [
                'name' => 'AAI Recruitment Careers',
                'source_url' => 'https://www.aai.aero/en/careers/recruitment',
                'selectors_config' => [
                    'driver' => 'psu',
                    'official_url' => 'https://www.aai.aero',
                    'notification_page' => 'https://www.aai.aero/en/careers/recruitment',
                    'update_frequency' => 'monthly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.aai-job',
                    'title_selector' => 'a.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catPsu->id,
                    'default_department_id' => $deptAAI->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 23 * * *',
            ],
            [
                'name' => 'FCI Careers Recruitment',
                'source_url' => 'https://fci.gov.in/recruitment.php',
                'selectors_config' => [
                    'driver' => 'psu',
                    'official_url' => 'https://fci.gov.in',
                    'notification_page' => 'https://fci.gov.in/recruitment.php',
                    'update_frequency' => 'monthly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.fci-job',
                    'title_selector' => 'a.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catPsu->id,
                    'default_department_id' => $deptFCI->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 23 * * *',
            ],
            [
                'name' => 'ESIC Careers Recruitment',
                'source_url' => 'https://www.esic.gov.in/recruitments',
                'selectors_config' => [
                    'driver' => 'psu',
                    'official_url' => 'https://www.esic.gov.in',
                    'notification_page' => 'https://www.esic.gov.in/recruitments',
                    'update_frequency' => 'monthly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.esic-job',
                    'title_selector' => 'a.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catHealth->id,
                    'default_department_id' => $deptESIC->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 23 * * *',
            ],
            [
                'name' => 'EPFO Careers Recruitment',
                'source_url' => 'https://www.epfindia.gov.in/site_en/Recruitments.php',
                'selectors_config' => [
                    'driver' => 'psu',
                    'official_url' => 'https://www.epfindia.gov.in',
                    'notification_page' => 'https://www.epfindia.gov.in/site_en/Recruitments.php',
                    'update_frequency' => 'monthly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.epfo-job',
                    'title_selector' => 'a.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catPsu->id,
                    'default_department_id' => $deptEPFO->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 23 * * *',
            ],

            // --- STATE PUBLIC SERVICE COMMISSIONS ---
            [
                'name' => 'Goa Public Service Commission Portal',
                'source_url' => 'https://gpsc.goa.gov.in/active-listings',
                'selectors_config' => [
                    'driver' => 'state_psc',
                    'official_url' => 'https://gpsc.goa.gov.in',
                    'notification_page' => 'https://gpsc.goa.gov.in/active-listings',
                    'update_frequency' => 'daily',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'headless',
                    'item_selector' => 'table.gpsc-table tr',
                    'title_selector' => 'td.gpsc-title',
                    'deadline_selector' => 'td.gpsc-date',
                    'default_category_id' => $catCivil->id,
                    'default_department_id' => $deptGPSC->id,
                    'default_state_id' => $stateGoa->id,
                ],
                'cron_expression' => '0 0 * * *',
            ],
            [
                'name' => 'Uttar Pradesh Public Service Commission',
                'source_url' => 'https://uppsc.up.nic.in/active-recruitments',
                'selectors_config' => [
                    'driver' => 'state_psc',
                    'official_url' => 'https://uppsc.up.nic.in',
                    'notification_page' => 'https://uppsc.up.nic.in/active-recruitments',
                    'update_frequency' => 'daily',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML', 'PDF'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'high',
                    'crawler_type' => 'http',
                    'item_selector' => 'table.uppsc-table tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.date',
                    'default_category_id' => $catCivil->id,
                    'default_department_id' => $deptUPPSC->id,
                    'default_state_id' => $stateUP->id,
                ],
                'cron_expression' => '0 1 * * *',
            ],
            [
                'name' => 'Andhra Pradesh Public Service Commission Portal',
                'source_url' => 'https://psc.ap.gov.in/active-listings',
                'selectors_config' => [
                    'driver' => 'state_psc',
                    'official_url' => 'https://psc.ap.gov.in',
                    'notification_page' => 'https://psc.ap.gov.in/active-listings',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'table.appsc-table tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.date',
                    'default_category_id' => $catCivil->id,
                    'default_department_id' => $deptAPPSC->id,
                    'default_state_id' => $stateAP->id,
                ],
                'cron_expression' => '0 1 * * *',
            ],
            [
                'name' => 'Assam Public Service Commission Portal',
                'source_url' => 'https://apsc.nic.in/active-recruitments',
                'selectors_config' => [
                    'driver' => 'state_psc',
                    'official_url' => 'https://apsc.nic.in',
                    'notification_page' => 'https://apsc.nic.in/active-recruitments',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'table.apsc-table tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.date',
                    'default_category_id' => $catCivil->id,
                    'default_department_id' => $deptAPSC->id,
                    'default_state_id' => $stateAS->id,
                ],
                'cron_expression' => '0 2 * * *',
            ],
            [
                'name' => 'Bihar Public Service Commission Portal',
                'source_url' => 'https://bpsc.bih.nic.in/active-recruitments',
                'selectors_config' => [
                    'driver' => 'state_psc',
                    'official_url' => 'https://bpsc.bih.nic.in',
                    'notification_page' => 'https://bpsc.bih.nic.in/active-recruitments',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'table.bpsc-table tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.date',
                    'default_category_id' => $catCivil->id,
                    'default_department_id' => $deptBPSC->id,
                    'default_state_id' => $stateBR->id,
                ],
                'cron_expression' => '0 2 * * *',
            ],
            [
                'name' => 'Chhattisgarh Public Service Commission Portal',
                'source_url' => 'https://psc.cg.gov.in/active-listings',
                'selectors_config' => [
                    'driver' => 'state_psc',
                    'official_url' => 'https://psc.cg.gov.in',
                    'notification_page' => 'https://psc.cg.gov.in/active-listings',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'table.cgpsc-table tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.date',
                    'default_category_id' => $catCivil->id,
                    'default_department_id' => $deptCGPSC->id,
                    'default_state_id' => $stateCG->id,
                ],
                'cron_expression' => '0 3 * * *',
            ],
            [
                'name' => 'Gujarat Public Service Commission Portal',
                'source_url' => 'https://gpsc.gujarat.gov.in/active-listings',
                'selectors_config' => [
                    'driver' => 'state_psc',
                    'official_url' => 'https://gpsc.gujarat.gov.in',
                    'notification_page' => 'https://gpsc.gujarat.gov.in/active-listings',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'table.gpscgj-table tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.date',
                    'default_category_id' => $catCivil->id,
                    'default_department_id' => $deptGPSCGJ->id,
                    'default_state_id' => $stateGJ->id,
                ],
                'cron_expression' => '0 3 * * *',
            ],
            [
                'name' => 'Haryana Public Service Commission Portal',
                'source_url' => 'https://hpsc.gov.in/active-listings',
                'selectors_config' => [
                    'driver' => 'state_psc',
                    'official_url' => 'https://hpsc.gov.in',
                    'notification_page' => 'https://hpsc.gov.in/active-listings',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'table.hpsc-table tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.date',
                    'default_category_id' => $catCivil->id,
                    'default_department_id' => $deptHPSC->id,
                    'default_state_id' => $stateHR->id,
                ],
                'cron_expression' => '0 4 * * *',
            ],
            [
                'name' => 'Himachal Pradesh Public Service Commission Portal',
                'source_url' => 'https://hppsc.hp.gov.in/active-listings',
                'selectors_config' => [
                    'driver' => 'state_psc',
                    'official_url' => 'https://hppsc.hp.gov.in',
                    'notification_page' => 'https://hppsc.hp.gov.in/active-listings',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'table.hppsc-table tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.date',
                    'default_category_id' => $catCivil->id,
                    'default_department_id' => $deptHPPSC->id,
                    'default_state_id' => $stateHP->id,
                ],
                'cron_expression' => '0 4 * * *',
            ],
            [
                'name' => 'Jharkhand Public Service Commission Portal',
                'source_url' => 'https://jpsc.gov.in/active-listings',
                'selectors_config' => [
                    'driver' => 'state_psc',
                    'official_url' => 'https://jpsc.gov.in',
                    'notification_page' => 'https://jpsc.gov.in/active-listings',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'table.jpsc-table tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.date',
                    'default_category_id' => $catCivil->id,
                    'default_department_id' => $deptJPSC->id,
                    'default_state_id' => $stateJH->id,
                ],
                'cron_expression' => '0 5 * * *',
            ],
            [
                'name' => 'Karnataka Public Service Commission Portal',
                'source_url' => 'https://kpsc.kar.nic.in/active-listings',
                'selectors_config' => [
                    'driver' => 'state_psc',
                    'official_url' => 'https://kpsc.kar.nic.in',
                    'notification_page' => 'https://kpsc.kar.nic.in/active-listings',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'table.kpsc-table tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.date',
                    'default_category_id' => $catCivil->id,
                    'default_department_id' => $deptKPSC->id,
                    'default_state_id' => $stateKar->id,
                ],
                'cron_expression' => '0 5 * * *',
            ],
            [
                'name' => 'Kerala Public Service Commission Portal',
                'source_url' => 'https://keralapsc.gov.in/active-listings',
                'selectors_config' => [
                    'driver' => 'state_psc',
                    'official_url' => 'https://keralapsc.gov.in',
                    'notification_page' => 'https://keralapsc.gov.in/active-listings',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'table.keralapsc-table tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.date',
                    'default_category_id' => $catCivil->id,
                    'default_department_id' => $deptKeralapsc->id,
                    'default_state_id' => $stateKL->id,
                ],
                'cron_expression' => '0 6 * * *',
            ],
            [
                'name' => 'Madhya Pradesh Public Service Commission Portal',
                'source_url' => 'https://mppsc.mp.gov.in/active-listings',
                'selectors_config' => [
                    'driver' => 'state_psc',
                    'official_url' => 'https://mppsc.mp.gov.in',
                    'notification_page' => 'https://mppsc.mp.gov.in/active-listings',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'table.mppsc-table tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.date',
                    'default_category_id' => $catCivil->id,
                    'default_department_id' => $deptMPPSC->id,
                    'default_state_id' => $stateMP->id,
                ],
                'cron_expression' => '0 6 * * *',
            ],
            [
                'name' => 'Maharashtra Public Service Commission Portal',
                'source_url' => 'https://mpsc.gov.in/active-listings',
                'selectors_config' => [
                    'driver' => 'state_psc',
                    'official_url' => 'https://mpsc.gov.in',
                    'notification_page' => 'https://mpsc.gov.in/active-listings',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'table.mpsc-table tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.date',
                    'default_category_id' => $catCivil->id,
                    'default_department_id' => $deptMPSC->id,
                    'default_state_id' => $stateMaha->id,
                ],
                'cron_expression' => '0 7 * * *',
            ],
            [
                'name' => 'Odisha Public Service Commission Portal',
                'source_url' => 'https://opsc.gov.in/active-listings',
                'selectors_config' => [
                    'driver' => 'state_psc',
                    'official_url' => 'https://opsc.gov.in',
                    'notification_page' => 'https://opsc.gov.in/active-listings',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'table.opsc-table tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.date',
                    'default_category_id' => $catCivil->id,
                    'default_department_id' => $deptOPSC->id,
                    'default_state_id' => $stateOD->id,
                ],
                'cron_expression' => '0 7 * * *',
            ],
            [
                'name' => 'Punjab Public Service Commission Portal',
                'source_url' => 'https://ppsc.gov.in/active-listings',
                'selectors_config' => [
                    'driver' => 'state_psc',
                    'official_url' => 'https://ppsc.gov.in',
                    'notification_page' => 'https://ppsc.gov.in/active-listings',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'table.ppsc-table tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.date',
                    'default_category_id' => $catCivil->id,
                    'default_department_id' => $deptPPSC->id,
                    'default_state_id' => $statePB->id,
                ],
                'cron_expression' => '0 8 * * *',
            ],
            [
                'name' => 'Rajasthan Public Service Commission Portal',
                'source_url' => 'https://rpsc.rajasthan.gov.in/active-listings',
                'selectors_config' => [
                    'driver' => 'state_psc',
                    'official_url' => 'https://rpsc.rajasthan.gov.in',
                    'notification_page' => 'https://rpsc.rajasthan.gov.in/active-listings',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'table.rpsc-table tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.date',
                    'default_category_id' => $catCivil->id,
                    'default_department_id' => $deptRPSC->id,
                    'default_state_id' => $stateRJ->id,
                ],
                'cron_expression' => '0 8 * * *',
            ],
            [
                'name' => 'Tamil Nadu Public Service Commission Portal',
                'source_url' => 'https://tnpsc.gov.in/active-listings',
                'selectors_config' => [
                    'driver' => 'state_psc',
                    'official_url' => 'https://tnpsc.gov.in',
                    'notification_page' => 'https://tnpsc.gov.in/active-listings',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'table.tnpsc-table tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.date',
                    'default_category_id' => $catCivil->id,
                    'default_department_id' => $deptTNPSC->id,
                    'default_state_id' => $stateTN->id,
                ],
                'cron_expression' => '0 9 * * *',
            ],
            [
                'name' => 'Telangana State Public Service Commission Portal',
                'source_url' => 'https://tspsc.gov.in/active-listings',
                'selectors_config' => [
                    'driver' => 'state_psc',
                    'official_url' => 'https://tspsc.gov.in',
                    'notification_page' => 'https://tspsc.gov.in/active-listings',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'table.tspsc-table tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.date',
                    'default_category_id' => $catCivil->id,
                    'default_department_id' => $deptTSPSC->id,
                    'default_state_id' => $stateTG->id,
                ],
                'cron_expression' => '0 9 * * *',
            ],
            [
                'name' => 'West Bengal Public Service Commission Portal',
                'source_url' => 'https://psc.wb.gov.in/active-listings',
                'selectors_config' => [
                    'driver' => 'state_psc',
                    'official_url' => 'https://psc.wb.gov.in',
                    'notification_page' => 'https://psc.wb.gov.in/active-listings',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'table.wbpsc-table tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.date',
                    'default_category_id' => $catCivil->id,
                    'default_department_id' => $deptWBPSC->id,
                    'default_state_id' => $stateWB->id,
                ],
                'cron_expression' => '0 10 * * *',
            ],

            // --- HIGH COURTS & DISTRICT COURTS ---
            [
                'name' => 'Delhi High Court Opportunities',
                'source_url' => 'https://delhihighcourt.nic.in/recruitment',
                'selectors_config' => [
                    'driver' => 'high_court',
                    'official_url' => 'https://delhihighcourt.nic.in',
                    'notification_page' => 'https://delhihighcourt.nic.in/recruitment',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML', 'PDF'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'high',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.hc-rec-row',
                    'title_selector' => 'a.title-link',
                    'deadline_selector' => 'span.end-date',
                    'default_category_id' => $catJudicial->id,
                    'default_department_id' => $deptDHC->id,
                    'default_state_id' => $stateDelhi->id,
                ],
                'cron_expression' => '0 2 * * *',
            ],
            [
                'name' => 'Delhi District Courts Job Board',
                'source_url' => 'https://delhidistrictcourts.nic.in/recruitment',
                'selectors_config' => [
                    'driver' => 'high_court',
                    'official_url' => 'https://delhidistrictcourts.nic.in',
                    'notification_page' => 'https://delhidistrictcourts.nic.in/recruitment',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML', 'PDF'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.court-item',
                    'title_selector' => 'h4.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catJudicial->id,
                    'default_department_id' => $deptDDC->id,
                    'default_state_id' => $stateDelhi->id,
                ],
                'cron_expression' => '0 3 * * *',
            ],

            // --- MUNICIPAL CORPORATIONS & SMART CITIES ---
            [
                'name' => 'Municipal Corporation of Delhi Careers',
                'source_url' => 'https://mcdonline.nic.in/careers',
                'selectors_config' => [
                    'driver' => 'municipal',
                    'official_url' => 'https://mcdonline.nic.in',
                    'notification_page' => 'https://mcdonline.nic.in/careers',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'cookie',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'yes',
                    'priority' => 'medium',
                    'crawler_type' => 'headless',
                    'item_selector' => 'table.mcd-jobs tr',
                    'title_selector' => 'td.job-title',
                    'deadline_selector' => 'td.expiry',
                    'default_category_id' => $catMunicipal->id,
                    'default_department_id' => $deptMCD->id,
                    'default_state_id' => $stateDelhi->id,
                ],
                'cron_expression' => '0 4 * * *',
            ],
            [
                'name' => 'Pune Smart City Careers',
                'source_url' => 'https://punesmartcity.in/careers',
                'selectors_config' => [
                    'driver' => 'municipal',
                    'official_url' => 'https://punesmartcity.in',
                    'notification_page' => 'https://punesmartcity.in/careers',
                    'update_frequency' => 'monthly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML', 'PDF'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'low',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.sc-job-item',
                    'title_selector' => 'h3.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catMunicipal->id,
                    'default_department_id' => $deptPuneSC->id,
                    'default_state_id' => $stateMaha->id,
                ],
                'cron_expression' => '0 5 * * *',
            ],

            // --- UNIVERSITIES & ACADEMIC ---
            [
                'name' => 'Delhi University Careers',
                'source_url' => 'https://du.ac.in/recruitment',
                'selectors_config' => [
                    'driver' => 'academic',
                    'official_url' => 'https://du.ac.in',
                    'notification_page' => 'https://du.ac.in/recruitment',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.du-job-item',
                    'title_selector' => 'a.job-title',
                    'deadline_selector' => 'span.expiry',
                    'default_category_id' => $catAcademic->id,
                    'default_department_id' => $deptDU->id,
                    'default_state_id' => $stateDelhi->id,
                ],
                'cron_expression' => '0 7 * * *',
            ],
            [
                'name' => 'AIIMS Delhi Recruitment Board',
                'source_url' => 'https://aiims.edu/recruitment',
                'selectors_config' => [
                    'driver' => 'academic',
                    'official_url' => 'https://aiims.edu',
                    'notification_page' => 'https://aiims.edu/recruitment',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML', 'PDF'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'yes',
                    'priority' => 'high',
                    'crawler_type' => 'playwright',
                    'item_selector' => 'table.aiims-table tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.date',
                    'default_category_id' => $catAcademic->id,
                    'default_department_id' => $deptAIIMS->id,
                    'default_state_id' => $stateDelhi->id,
                ],
                'cron_expression' => '0 8 * * *',
            ],

            // --- RAILWAYS & BANKING ---
            [
                'name' => 'RRB Recruitment Board Feed',
                'source_url' => 'https://rrbapply.gov.in/recruitment-feed',
                'selectors_config' => [
                    'driver' => 'railway',
                    'official_url' => 'https://rrbapply.gov.in',
                    'notification_page' => 'https://rrbapply.gov.in/recruitment-feed',
                    'update_frequency' => 'daily',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'high',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.rrb-item',
                    'title_selector' => 'h3.rrb-title',
                    'deadline_selector' => 'span.rrb-date',
                    'default_category_id' => $catRail->id,
                    'default_department_id' => $deptRRB->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 12 * * *',
            ],
            [
                'name' => 'SBI Careers Recruitment Portal',
                'source_url' => 'https://sbi.co.in/careers/active-listings',
                'selectors_config' => [
                    'driver' => 'banking',
                    'official_url' => 'https://sbi.co.in',
                    'notification_page' => 'https://sbi.co.in/careers/active-listings',
                    'update_frequency' => 'daily',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'high',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.sbi-job',
                    'title_selector' => 'a.sbi-title',
                    'deadline_selector' => 'span.sbi-deadline',
                    'default_category_id' => $catBank->id,
                    'default_department_id' => $deptSBI->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 6 * * *',
            ],

            // --- AGRICULTURE, FOREST & MINING ---
            [
                'name' => 'ICAR Agriculture Careers',
                'source_url' => 'https://icar.org.in/recruitment',
                'selectors_config' => [
                    'driver' => 'natural_resources',
                    'official_url' => 'https://icar.org.in',
                    'notification_page' => 'https://icar.org.in/recruitment',
                    'update_frequency' => 'weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML', 'PDF'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'medium',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.icar-job-row',
                    'title_selector' => 'a.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catNatural->id,
                    'default_department_id' => $deptICAR->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 10 * * *',
            ],

            // --- HEALTH, EDUCATION & RESEARCH ---
            [
                'name' => 'National Health Mission Board',
                'source_url' => 'https://nhm.gov.in/recruitment',
                'selectors_config' => [
                    'driver' => 'academic',
                    'official_url' => 'https://nhm.gov.in',
                    'notification_page' => 'https://nhm.gov.in/recruitment',
                    'update_frequency' => 'twice_weekly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML', 'PDF'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'high',
                    'crawler_type' => 'http',
                    'item_selector' => 'div.nhm-job-item',
                    'title_selector' => 'a.title',
                    'deadline_selector' => 'span.date',
                    'default_category_id' => $catHealth->id,
                    'default_department_id' => $deptNHM->id,
                    'default_state_id' => $statePanIndia->id,
                ],
                'cron_expression' => '0 13 * * *',
            ],

            // --- DISTRICT RECRUITMENT BOARDS ---
            [
                'name' => 'District Selection Committee UP',
                'source_url' => 'https://districtselection.up.nic.in/recruitment',
                'selectors_config' => [
                    'driver' => 'state_psc',
                    'official_url' => 'https://districtselection.up.nic.in',
                    'notification_page' => 'https://districtselection.up.nic.in/recruitment',
                    'update_frequency' => 'monthly',
                    'authentication_type' => 'none',
                    'rss_availability' => 'no',
                    'formats' => ['HTML'],
                    'has_captcha' => 'no',
                    'is_dynamic' => 'no',
                    'priority' => 'low',
                    'crawler_type' => 'http',
                    'item_selector' => 'table.dsc-table tr',
                    'title_selector' => 'td.title',
                    'deadline_selector' => 'td.date',
                    'default_category_id' => $catCivil->id,
                    'default_department_id' => $deptDSC->id,
                    'default_state_id' => $stateUP->id,
                ],
                'cron_expression' => '0 15 * * *',
            ],
        ];

        // 5. Seed Sources
        foreach ($sources as $src) {
            ScrapingSource::updateOrCreate(
                ['source_url' => $src['source_url']],
                [
                    'name' => $src['name'],
                    'source_type' => 'html',
                    'selectors_config' => $src['selectors_config'],
                    'cron_expression' => $src['cron_expression'],
                    'is_active' => true,
                ]
            );
        }
    }
}
